train_file: ['../data/finetune/coco_karpathy/coco_karpathy_train.json']
val_file: '../data/finetune/coco_karpathy/coco_karpathy_val.json'
test_file: '../data/finetune/coco_karpathy/coco_karpathy_test.json'

image_root: '../images/coco/'
val_gt_file: '../data/finetune/coco_karpathy/coco_karpathy_val_gt.json'
test_gt_file: '../data/finetune/coco_karpathy/coco_karpathy_test_gt.json'

## Vision Encoder
use_beit_v2: True
vision_config: 'configs/model/config_beit2_base.json'
image_res: 384
patch_size: 16
local_attn_depth: -1

## Text Encoder (& Cross Encoder)
text_encoder: '../data/roberta-base'
text_num_hidden_layers: 12
text_fusion_start_at: 12
fusion_num_hidden_layers: 12
fusion_fusion_start_at: 0


## Training
batch_size_train: 32
batch_size_test: 32
max_tokens: 40 
label_smoothing: 0.1


## generation configs
max_length: 20
min_length: 5
num_beams: 3
prompt: 'a picture of '


## Other Settings
optimizer: {opt: adamW, lr: 1e-5, weight_decay: 0.01, lr_mult: 2}
schedular: {sched: linear, lr: 1e-5, epochs: 5, num_warmup_steps: 0.1}
start_eval: 0  # epoch index

