task_name: dtd
dataset: '../images/dtd'

## Vision Encoder
# use_clip_vit: False
# vision_config: 'configs/model/config_clipvitB.json'
# image_res: 224
# patch_size: 16

# use_swin: False
# vision_config: 'configs/model/config_swinB_224.json'
# image_res: 224
# patch_size: 32

use_beit_v2: True
vision_config: 'configs/model/config_beit2_base.json'
image_res: 224
patch_size: 16
local_attn_depth: -1

## Text Encoder (& Cross Encoder)
text_encoder: '../data/roberta-base'
text_num_hidden_layers: 0
text_fusion_start_at: 0
fusion_num_hidden_layers: 0
fusion_fusion_start_at: 0

## Training
batch_size_train: 512 #256
batch_size_test: 512
num_readers: 4
mixup: 0.8
cutmix: 1.0
cutmix_minmax:
mixup_prob: 1.0
mixup_switch_prob: 0.5
mixup_mode: 'batch'
smoothing: 0.1
num_labels: 1000
color_jitter: 
aa: 'rand-m9-mstd0.5-inc1'
reprob: 0.25
remode: 'pixel'
recount: 1
is_lp: True

## Other Settings
optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.02, momentum: 0.9}
schedular: {lr: 2e-5, min_lr: 0, epochs: 100, warmup_epochs: 10 }