train_file:
validation_file:
test_file:
glue_datasets: ../glue/glue_datasets

# task info
task_name: rte
num_labels: 3
max_length: 128
per_device_train_batch_size: 16
per_device_eval_batch_size: 8
learning_rate: 1e-5
weight_decay: 0.0
num_train_epochs: 20
max_train_steps: 
pad_to_max_length: False
use_slow_tokenizer: False
gradient_accumulation_steps: 1
num_warmup_steps: 0
seed: 42
lr_scheduler_type: linear #choices=["linear", "cosine", "cosine_with_restarts", "polynomial", "constant", "constant_with_warmup"]
output_dir: 
checkpoint:
ckpt_frequent: 5

## Vision Encoder
use_beit_v2: True
vision_config: 'configs/model/config_beit2_base.json'
image_res: 384
patch_size: 16
local_attn_depth: -1

## Text Encoder (& Cross Encoder)
text_encoder: '../data/roberta-base'
text_num_hidden_layers: 12
text_fusion_start_at: 12
fusion_num_hidden_layers: 0
fusion_fusion_start_at: 0

use_huggingface_models: False
model_name_or_path: bert-base-cased







