train_file: ['../data/finetune/refcoco+_train.json']
test_file: ['../data/finetune/refcoco+_val.json','../data/finetune/refcoco+_test.json']

refcoco_data: '../data/finetune/'
det_file: '../data/finetune/refcoco+/dets.json'
coco_file: '../data/finetune/refcoco+/cocos.json'

image_root: '../images/coco/'

careful_hflip: True  # first check whether 'left' or 'right' in captions

## Vision Encoder
use_beit_v2: True
vision_config: 'configs/model/config_beit2_base.json'
image_res: 384
patch_size: 16
local_attn_depth: -1

## Text Encoder (& Cross Encoder)
text_encoder: '../data/roberta-base'
text_num_hidden_layers: 12
text_fusion_start_at: 12
fusion_num_hidden_layers: 12
fusion_fusion_start_at: 0

## Training
batch_size: 20
max_tokens: 40


## Other Settings
optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.01, lr_mult: 2}
schedular: {sched: linear, lr: 2e-5, epochs: 15, num_warmup_steps: 0.1}

